---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: kafka-0.8
    run_list:
      - recipe[apt]
      - recipe[kafka]
    attributes:
      kafka:
        version: 0.8.0
